from pathlib import Path
import tempfile
import unittest

from trymtex.config import TrymtexConfig
from trymtex.semantic import apply_semantic_fixes, run_semantic


class SemanticTests(unittest.TestCase):
    def test_semantic_detects_labels_refs_and_repeated_words(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text(
                "\\section{Intro}\\label{sec:intro}\n"
                "See \\ref{sec:missing}. This is is repeated.\n"
                "\\section{Again}\\label{sec:intro}\n",
                encoding="utf-8",
            )

            issues = run_semantic([tex], TrymtexConfig())
            rules = [issue.rule for issue in issues]

            self.assertIn("duplicate-label", rules)
            self.assertIn("undefined-reference", rules)
            self.assertIn("unused-label", rules)
            self.assertIn("repeated-word", rules)

    def test_semantic_autofixes_local_safe_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text(
                "\\usepackage{amsmath}\n"
                "\\usepackage{amsmath}\n"
                "This is is duplicated at https://example.com/page.\n",
                encoding="utf-8",
            )

            issues = run_semantic([tex], TrymtexConfig())
            fixes, changed, changes = apply_semantic_fixes(issues, TrymtexConfig(), dry_run=False, backup=False)

            self.assertIn(tex, changed)
            self.assertTrue(changes)
            self.assertGreaterEqual(sum(1 for fix in fixes if fix.changed), 2)
            text = tex.read_text(encoding="utf-8")
            self.assertEqual(text.count("\\usepackage{amsmath}"), 1)
            self.assertIn("This is duplicated", text)
            self.assertIn("\\url{https://example.com/page}", text)

    def test_duplicate_usepackage_is_file_local(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            one = root / "one.tex"
            two = root / "two.tex"
            one.write_text("\\usepackage{amsmath}\n", encoding="utf-8")
            two.write_text("\\usepackage{amsmath}\n", encoding="utf-8")

            issues = run_semantic([one, two], TrymtexConfig())

            self.assertNotIn("duplicate-usepackage", [issue.rule for issue in issues])

    def test_math_and_typography_autofixes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text(
                'Pages 1-2 say "hello"... and word - word.\n'
                "$sin x , cos y$\n",
                encoding="utf-8",
            )

            issues = run_semantic([tex], TrymtexConfig())
            fixes, _, _ = apply_semantic_fixes(issues, TrymtexConfig(), dry_run=False, backup=False)

            text = tex.read_text(encoding="utf-8")
            self.assertGreaterEqual(sum(1 for fix in fixes if fix.changed), 5)
            self.assertIn("Pages 1--2", text)
            self.assertIn("``hello''", text)
            self.assertIn("\\ldots{}", text)
            self.assertIn("word---word", text)
            self.assertIn("\\(\\sin x, \\cos y\\)", text)

    def test_math_rules_only_touch_math_spans(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text("The word sin is prose, but $sin x$ is math.\n", encoding="utf-8")

            issues = run_semantic([tex], TrymtexConfig())
            apply_semantic_fixes(issues, TrymtexConfig(), dry_run=False, backup=False)

            self.assertEqual(tex.read_text(encoding="utf-8"), "The word sin is prose, but \\(\\sin x\\) is math.\n")

    def test_macro_duplicates_are_fixed_but_conflicts_are_not(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text(
                "\\newcommand{\\foo}{x}\n"
                "\\newcommand{\\foo}{x}\n"
                "\\newcommand{\\foo}{y}\n",
                encoding="utf-8",
            )

            issues = run_semantic([tex], TrymtexConfig())
            fixes, _, _ = apply_semantic_fixes(issues, TrymtexConfig(), dry_run=False, backup=False)

            text = tex.read_text(encoding="utf-8")
            self.assertEqual(text.count("\\newcommand{\\foo}{x}"), 1)
            self.assertIn("\\newcommand{\\foo}{y}", text)
            self.assertTrue(any(not fix.changed and "conflicting" in fix.reason for fix in fixes))

    def test_generated_and_verbatim_content_is_not_rewritten(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            generated = Path(tmp) / "generated.tex"
            generated.write_text("% Generated by tool. Do not edit.\nThis is is bad.\n", encoding="utf-8")
            verbatim = Path(tmp) / "verbatim.tex"
            verbatim.write_text("\\begin{verbatim}\nThis is is bad at https://example.com.\n\\end{verbatim}\n", encoding="utf-8")

            generated_issues = run_semantic([generated], TrymtexConfig())
            verbatim_issues = run_semantic([verbatim], TrymtexConfig())

            self.assertEqual(generated_issues, [])
            self.assertEqual(verbatim_issues, [])

    def test_math_delimiter_autofixes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text(
                "Inline $a+b$ and display $$c+d$$.\n"
                "$$\n"
                "e+f\n"
                "$$\n",
                encoding="utf-8",
            )

            issues = run_semantic([tex], TrymtexConfig())
            apply_semantic_fixes(issues, TrymtexConfig(), dry_run=False, backup=False)

            self.assertEqual(
                tex.read_text(encoding="utf-8"),
                "Inline \\(a+b\\) and display \\[c+d\\].\n"
                "\\[\n"
                "e+f\n"
                "\\]\n",
            )

    def test_eqnarray_font_and_centerline_autofixes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text(
                "\\begin{eqnarray*}\n"
                "x&=&y\n"
                "\\end{eqnarray*}\n"
                "{\\bf Bold} and {\\it italic}.\n"
                "\\centerline{A title}\n",
                encoding="utf-8",
            )

            issues = run_semantic([tex], TrymtexConfig())
            apply_semantic_fixes(issues, TrymtexConfig(), dry_run=False, backup=False)

            text = tex.read_text(encoding="utf-8")
            self.assertIn("\\begin{align*}", text)
            self.assertIn("\\end{align*}", text)
            self.assertIn("\\textbf{Bold}", text)
            self.assertIn("\\textit{italic}", text)
            self.assertIn("\\begin{center}A title\\end{center}", text)

    def test_inline_math_delimiter_skips_numeric_currency_like_text(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tex = Path(tmp) / "paper.tex"
            tex.write_text("The price is $12.50$ today.\n", encoding="utf-8")

            issues = run_semantic([tex], TrymtexConfig())

            self.assertNotIn("inline-math-delimiter", [issue.rule for issue in issues])


if __name__ == "__main__":
    unittest.main()
